# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: v1beta-ci

on:
  push:
    branches: [ v1beta ]
  pull_request:
    branches: [ v1beta ]
    types: [opened, synchronize]

jobs:
  build:

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    environment: v1beta

    steps:
    - uses: actions/checkout@v2
    - name: uitest
      id: uitest
      run: npm install && npm test
    - name: prmerged
      if: github.event_name == 'push'
      id: prmerged
      run: |
          echo pr has been merged and closed
